apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-microservice-service-deployment
  labels:
    app: bar-microservice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar-microservice-service-pod
  template:
    metadata:
      labels:
        app: bar-microservice-service-pod
    spec:
      containers:
        - name: bar-microservice
          image: bar-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password